-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.article_likes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  article_id uuid NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT article_likes_pkey PRIMARY KEY (id),
  CONSTRAINT article_likes_article_id_fkey FOREIGN KEY (article_id) REFERENCES public.articles(id),
  CONSTRAINT article_likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.articles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  excerpt text,
  content text NOT NULL,
  featured_image_url character varying NOT NULL,
  category USER-DEFINED NOT NULL,
  status USER-DEFINED DEFAULT 'draft'::article_status,
  read_time integer DEFAULT 5,
  views integer DEFAULT 0,
  tags ARRAY NOT NULL,
  published_at timestamp with time zone,
  archived_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT articles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.attributes (
  attribute_id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  category_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT attributes_pkey PRIMARY KEY (attribute_id),
  CONSTRAINT attributes_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  parent_category_id uuid,
  name text NOT NULL,
  desc text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone,
  archived_at timestamp without time zone,
  archive_reason text,
  CONSTRAINT categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.comment_reactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  comment_id uuid NOT NULL,
  user_id uuid NOT NULL,
  reaction_type USER-DEFINED DEFAULT 'like'::reaction_type,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT comment_reactions_pkey PRIMARY KEY (id),
  CONSTRAINT comment_reactions_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES public.comments(id),
  CONSTRAINT comment_reactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  article_id uuid NOT NULL,
  user_id uuid NOT NULL,
  parent_id uuid,
  content text NOT NULL,
  is_approved boolean DEFAULT true,
  is_admin_reply boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT comments_pkey PRIMARY KEY (id),
  CONSTRAINT comments_article_id_fkey FOREIGN KEY (article_id) REFERENCES public.articles(id),
  CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT comments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.comments(id)
);
CREATE TABLE public.communities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_by uuid DEFAULT auth.uid(),
  name text NOT NULL,
  description text NOT NULL,
  slug text UNIQUE,
  image_url text,
  banner_url text,
  rules text,
  privacy text DEFAULT 'public'::text CHECK (privacy = ANY (ARRAY['public'::text, 'private'::text])),
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'active'::text, 'inactive'::text, 'archived'::text])),
  is_approved boolean DEFAULT false,
  approved_by uuid,
  approved_at timestamp without time zone,
  total_members integer DEFAULT 0,
  male_count integer DEFAULT 0,
  female_count integer DEFAULT 0,
  post_count integer DEFAULT 0,
  comment_count integer DEFAULT 0,
  tags ARRAY DEFAULT '{}'::text[],
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  archived_at timestamp without time zone,
  archive_reason text,
  CONSTRAINT communities_pkey PRIMARY KEY (id),
  CONSTRAINT communities_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT communities_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.community_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  community_id uuid,
  user_id uuid,
  post_count integer DEFAULT 0,
  comment_count integer DEFAULT 0,
  role text DEFAULT 'member'::text CHECK (role = ANY (ARRAY['member'::text, 'moderator'::text, 'admin'::text])),
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  joined_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT community_members_pkey PRIMARY KEY (id),
  CONSTRAINT community_members_community_id_fkey FOREIGN KEY (community_id) REFERENCES public.communities(id),
  CONSTRAINT community_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.contacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firstName text NOT NULL,
  lastName text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  subject text NOT NULL,
  message text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  status text DEFAULT 'pending'::text,
  updated_at timestamp without time zone,
  custom_subject text,
  CONSTRAINT contacts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cooperatives (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid(),
  name text NOT NULL,
  address text NOT NULL,
  barangay text NOT NULL,
  city text NOT NULL,
  postalCode text NOT NULL,
  image text,
  latitude text,
  longitude text,
  numOfReviews integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp without time zone,
  email text,
  phone text,
  completeAddress text,
  isApproved boolean DEFAULT false,
  region text,
  province text,
  CONSTRAINT cooperatives_pkey PRIMARY KEY (id),
  CONSTRAINT cooperatives_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.courier (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  license_front text NOT NULL,
  license_back text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL,
  archived_at timestamp without time zone,
  vehicle_type text NOT NULL,
  or_url text NOT NULL,
  cr_url text NOT NULL,
  archived_reason text,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  status text NOT NULL DEFAULT 'pending'::text,
  CONSTRAINT courier_pkey PRIMARY KEY (id),
  CONSTRAINT courier_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone NOT NULL,
  start_time time without time zone,
  end_time time without time zone,
  event_type USER-DEFINED NOT NULL DEFAULT 'seminar'::event_type,
  location text,
  is_online boolean DEFAULT false,
  meeting_link text,
  venue text,
  max_attendees integer,
  current_attendees integer DEFAULT 0,
  status USER-DEFINED DEFAULT 'draft'::event_status,
  featured_image text,
  registration_deadline timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.password_resets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  token_hash text NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  attempts integer DEFAULT 0,
  used boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  used_at timestamp with time zone,
  short_code character varying,
  CONSTRAINT password_resets_pkey PRIMARY KEY (id),
  CONSTRAINT password_resets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.post_comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  post_id uuid,
  author_id uuid,
  parent_id uuid,
  content text NOT NULL,
  upvote_count integer DEFAULT 0,
  downvote_count integer DEFAULT 0,
  reply_count integer DEFAULT 0,
  is_removed boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT post_comments_pkey PRIMARY KEY (id),
  CONSTRAINT post_comments_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id),
  CONSTRAINT post_comments_author_id_fkey FOREIGN KEY (author_id) REFERENCES auth.users(id),
  CONSTRAINT post_comments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.post_comments(id)
);
CREATE TABLE public.posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  community_id uuid,
  author_id uuid,
  title text NOT NULL,
  content text,
  post_type text DEFAULT 'text'::text CHECK (post_type = ANY (ARRAY['text'::text, 'link'::text, 'image'::text, 'poll'::text, 'video'::text])),
  url text,
  image_urls ARRAY,
  poll_options jsonb,
  is_pinned boolean DEFAULT false,
  is_removed boolean DEFAULT false,
  removed_by uuid,
  removed_at timestamp without time zone,
  removal_reason text,
  upvote_count integer DEFAULT 0,
  downvote_count integer DEFAULT 0,
  comment_count integer DEFAULT 0,
  view_count integer DEFAULT 0,
  share_count integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT posts_pkey PRIMARY KEY (id),
  CONSTRAINT posts_author_id_fkey1 FOREIGN KEY (author_id) REFERENCES public.users(id),
  CONSTRAINT posts_removed_by_fkey1 FOREIGN KEY (removed_by) REFERENCES public.users(id),
  CONSTRAINT posts_community_id_fkey FOREIGN KEY (community_id) REFERENCES public.communities(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_id uuid NOT NULL,
  coop_id uuid NOT NULL,
  name text NOT NULL,
  description text NOT NULL,
  unit_type text NOT NULL,
  images ARRAY DEFAULT '{}'::text[],
  is_featured boolean DEFAULT false,
  is_best_seller boolean DEFAULT false,
  is_new_arrival boolean DEFAULT false,
  status text DEFAULT '''active'''::text,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  archived_at timestamp without time zone,
  archive_reason text,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id),
  CONSTRAINT products_coop_id_fkey FOREIGN KEY (coop_id) REFERENCES public.cooperatives(id)
);
CREATE TABLE public.products_attributes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  attribute_id uuid NOT NULL,
  SKU text NOT NULL,
  price numeric NOT NULL,
  member_price numeric NOT NULL,
  stock integer NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  attribute_value text NOT NULL,
  CONSTRAINT products_attributes_pkey PRIMARY KEY (id),
  CONSTRAINT product_variants_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT products_attributes_attribute_id_fkey FOREIGN KEY (attribute_id) REFERENCES public.attributes(attribute_id)
);
CREATE TABLE public.supplier_product_attributes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  attribute_id uuid NOT NULL,
  attribute_value text NOT NULL,
  price numeric NOT NULL CHECK (price >= 0::numeric),
  stock_quantity integer NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
  sku text,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT supplier_product_attributes_pkey PRIMARY KEY (id),
  CONSTRAINT supplier_product_attributes_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.supplier_products(id),
  CONSTRAINT supplier_product_attributes_attribute_id_fkey FOREIGN KEY (attribute_id) REFERENCES public.attributes(attribute_id)
);
CREATE TABLE public.supplier_products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  supplier_id uuid NOT NULL,
  name character varying NOT NULL,
  description text NOT NULL,
  category_id uuid NOT NULL,
  unit_type character varying NOT NULL,
  images ARRAY NOT NULL,
  min_order_quantity integer NOT NULL DEFAULT 1,
  storage_requirements text NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  archived_at timestamp without time zone,
  archived_reason text,
  status text NOT NULL DEFAULT 'active'::text,
  CONSTRAINT supplier_products_pkey PRIMARY KEY (id),
  CONSTRAINT supplier_products_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT fk_supplier_products_category FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.suppliers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  type text NOT NULL,
  user_id uuid NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  address text NOT NULL,
  barangay text NOT NULL,
  city text NOT NULL,
  province text NOT NULL,
  region text NOT NULL,
  business_registration text,
  profile_image text,
  archive_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone,
  archived_at timestamp without time zone,
  status text NOT NULL DEFAULT 'pending'::text,
  CONSTRAINT suppliers_pkey PRIMARY KEY (id),
  CONSTRAINT suppliers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  first_name text,
  last_name text,
  phone text,
  email text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp without time zone,
  gender text,
  dob date,
  role text,
  image text,
  region text,
  province text,
  city text,
  barangay text,
  updated_at timestamp without time zone,
  address text,
  status text,
  email_verified boolean,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);